# Generated by Django 5.0.3 on 2024-04-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('emp_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_designation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
