# Generated by Django 5.0.3 on 2024-08-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDirectory',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('directory_name', models.CharField(max_length=100)),
                ('document_directory', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_directory',
                'managed': True,
            },
        ),
    ]
