# Generated by Django 5.1.7 on 2025-06-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employeedirectory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedirectory',
            options={},
        ),
        migrations.AlterModelTable(
            name='employeedirectory',
            table=None,
        ),
    ]
