# Generated by Django 5.1.7 on 2025-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employeeskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
